FROM node:22.16.0 AS build
ARG VITE_ENV=development
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM alpine:3.21
RUN apk update && apk add --no-cache nginx bash curl netcat-openbsd
COPY --from=build /app/dist/angular/browser /usr/share/nginx/html
COPY nginx.conf /etc/nginx/http.d/default.conf

HEALTHCHECK --interval=30s --timeout=10s --retries=3 \
  CMD curl -f http://localhost:80 || exit 1

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
