global: 
  scrape_interval: 60s

scrape_configs:
  - job_name: 'backend'
    ec2_sd_configs:
      - region: eu-central-1
        port: 9100
        filters:
          - name: tag:Name
            values: ['dotnet']
    relabel_configs:
      - source_labels: [__meta_ec2_tag_Name]
        target_label: instance_name

  - job_name: 'react-frontend'
    ec2_sd_configs:
      - region: eu-central-1
        port: 9100
        filters:
          - name: tag:Name
            values: ['react']
    relabel_configs:
      - source_labels: [__meta_ec2_tag_Name]
        target_label: instance_name

  - job_name: 'angular-frontend'
    ec2_sd_configs:
      - region: eu-central-1
        port: 9100
        filters:
          - name: tag:Name
            values: ['angular']
    relabel_configs:
      - source_labels: [__meta_ec2_tag_Name]
        target_label: instance_name

  - job_name: 'cloudwatch-exporter'
    static_configs:
      - targets: ['127.0.0.1:9106']  # або приватний IP інстансу
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: cloudwatch-exporter