global: 
  scrape_interval: 60s

scrape_configs:
  - job_name: 'backend'
    ec2_sd_configs:
      - region: eu-central-1
        port: 9100
        filters:
          - name: tag:Name
            values: ['dotnet']

  - job_name: 'react-frontend'
    ec2_sd_configs:
      - region: eu-central-1
        port: 9100
        filters:
          - name: tag:Name
            values: ['react']

  - job_name: 'angular-frontend'
    ec2_sd_configs:
      - region: eu-central-1
        port: 9100
        filters:
          - name: tag:Name
            values: ['angular']