# Use the official Postgres base image
FROM postgres:16

# Set environment variables (default values can be overridden at runtime)
ENV POSTGRES_USER=admin
ENV POSTGRES_PASSWORD=secret
ENV POSTGRES_DB=itm

# Expose Postgres default port
EXPOSE 5432
