name: ci angular

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/angular/**'
  pull_request:   
    branches:
        - main
    paths:
      - 'frontend/angular/**'       
   
jobs:
  test:
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    name: Run Tests for Angular
    uses: ./.github/workflows/test.yml
    with:
      microservice: angular
    secrets: inherit

  # Build Docker Image for Angular
  build:
    if: github.event_name == 'push'
    name: Build Angular Docker Image
    permissions:
      contents: read
      pull-requests: read
    uses: ./.github/workflows/build-and-push.yml
    with:
      microservice: angular
    secrets: inherit
