name: Build and Push Docker Image

on:
  workflow_call:
    inputs:
      microservice:
        type: string
        required: true
        description: 'Target microservice (react, angular, dotnet)'

  workflow_dispatch:
    inputs:
      microservice:
        description: 'Target microservice'
        required: true
        type: choice
        options:
          - react
          - angular
          - dotnet                
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set build context, Dockerfile and Repo 
        id: vars
        uses: ./.github/actions/set-var
        with:
          microservice: ${{ inputs.microservice }}
          docker_hub_username: ${{ secrets.DOCKER_HUB_USERNAME }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
    
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ${{ env.CONTEXT }}
          file: ${{ env.DOCKERFILE }}
          push: true
          tags: |
            ${{ env.REPO }}:latest
            ${{ env.REPO }}:${{ env.SHORT_SHA }}

      - name: Notify about successful build
        if: success()
        run: |
          echo "::notice::Successfully built and pushed ${{ inputs.microservice }} image with tags: latest, ${{ steps.vars.outputs.SHORT_SHA }}"