name: ci react

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/react/**'
  pull_request:   
    branches:
        - main
    paths:
      - 'frontend/react/**'      

jobs:
  test:
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    name: Run Tests for React
    uses: ./.github/workflows/test.yml
    with:
      microservice: react
    secrets: inherit

  # Build Docker Image for React
  build:
    if: github.event_name == 'push'
    name: Build React Docker Image
    permissions:
      contents: read
      pull-requests: read
    uses: ./.github/workflows/build-and-push.yml
    with:
      microservice: react
    secrets: inherit